<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Publisher API
 *
 * Uscreen Publisher API to controll user data and information
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@uscreen.tv
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.20
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace UScreen\Client;

use \UScreen\Client\Configuration;
use \SwUScreenagger\Client\ApiException;
use \UScreen\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  UScreen\Client
 * @author   UScreen Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
	    $dotenv = \Dotenv\Dotenv::createImmutable('.');
	    $dotenv->load();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for customersCustomerIdAccessesGet
     *
     * Get paginated list of accesses.
     *
     */
    public function testCustomersCustomerIdAccessesGet()
    {
    }

    /**
     * Test case for customersCustomerIdAccessesIdDelete
     *
     * Revoke access by ID.
     *
     */
    public function testCustomersCustomerIdAccessesIdDelete()
    {
    }

    /**
     * Test case for customersCustomerIdAccessesIdGet
     *
     * Get access by ID.
     *
     */
    public function testCustomersCustomerIdAccessesIdGet()
    {
    }

    /**
     * Test case for customersCustomerIdAccessesPost
     *
     * Grant access to a customer.
     *
     */
    public function testCustomersCustomerIdAccessesPost()
    {
    }

    /**
     * Test case for customersCustomerIdTokenizedUrlPost
     *
     * Generates a Single Sign-On link for a customer.
     *
     */
    public function testCustomersCustomerIdTokenizedUrlPost()
    {
    }

    /**
     * Test case for customersGet
     *
     * Get paginated list of customers.
     *
     */
    public function testCustomersGet()
    {
	    $api = \UScreen\UScreen::getApiService($_ENV['USCREEN_ENDPOINT'],
		    $_ENV['USCREEN_TOKEN']);

	    print_r($api->customersGet());


	    return $api;
    }

    /**
     * Test case for customersIdGet
     *
     * Get a customer information.
     *
     */
    public function testCustomersIdGet()
    {
    }

    /**
     * Test case for customersIdPut
     *
     * Update a customer information.
     *
     */
    public function testCustomersIdPut()
    {
    }

    /**
     * Test case for customersPost
     *
     * Invite a new customer.
     *
     */
    public function testCustomersPost()
    {
    }

    /**
     * Test case for offersGet
     *
     * Get paginated list of offers.
     *
     */
    public function testOffersGet()
    {
    }

    /**
     * Test case for offersIdGet
     *
     * Get an offer information.
     *
     */
    public function testOffersIdGet()
    {
    }

    /**
     * Test case for programsGet
     *
     * Get paginated list of programs.
     *
     */
    public function testProgramsGet()
    {
    }

    /**
     * Test case for programsIdGet
     *
     * Get a program information.
     *
     */
    public function testProgramsIdGet()
    {
    }

    /**
     * Test case for programsProgramIdChaptersGet
     *
     * Get list of chapters.
     *
     */
    public function testProgramsProgramIdChaptersGet()
    {
    }

    /**
     * Test case for programsProgramIdChaptersIdGet
     *
     * Get a chapter.
     *
     */
    public function testProgramsProgramIdChaptersIdGet()
    {
    }

    /**
     * Test case for themesBackupsIdRestorePut
     *
     * Restore backup.
     *
     */
    public function testThemesBackupsIdRestorePut()
    {
    }

    /**
     * Test case for themesBackupsPost
     *
     * Create backup.
     *
     */
    public function testThemesBackupsPost()
    {
    }

    /**
     * Test case for videosGet
     *
     * Get paginated list of videos.
     *
     */
    public function testVideosGet()
    {
    }

    /**
     * Test case for videosIdGet
     *
     * Get a video information.
     *
     */
    public function testVideosIdGet()
    {
    }
}
